spring:
  datasource:
    host: 154.219.125.98
    port: 3306
    username: root
    password: '${MYSQL_PASSWORD}'
  data:
    redis:
      host: 154.219.125.98
      port: 6379
      password: '${REDIS_PASSWORD}'
      database: 0

security:
  cookie:
    secure: false
    sameSite: Lax
    path: /
    httpOnly: false
  jwt:
    issuer: shopping.international
    audience: web
    secret-base64: w4Lw9...（Base64 编码的 256bit HMAC 密钥）
    clock-skew-seconds: 60
    access-token-validity-seconds: 259200 # 3 days
    refresh-token-validity-seconds: 2592000 # 30 days

logging:
  level:
    org.springframework.security: DEBUG